#*******************************************************************************
   #Filename:Makefile
   #Brief:
   #Author:Ravi Dubey
   #Date:3/14/2018
 #*****************************************************************************/

client.elf:client.c
	gcc -g -o client.elf client.c

clean:
	rm -f client.elf
